### ISSUE TITLE
AT+GSLP get Flash Read Error 1000

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-at#1]
hi
a test on DevKitC and AT+GSLP=2000 
i get an falling back and .. flash read error... falling back .. and new boot then is ok.
do i miss a second partion for bootloader? 
sdkconfig is single app, without OTA 

![6](https://cloud.githubusercontent.com/assets/16070445/22809356/21b06e6a-ef32-11e6-98eb-7f3a359f92d1.png)

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
No interest - ok
Close it

**Comment by xcguang** [comment]
Thanks for your interest in ESP32 ,we will reproduce it and fix it.

**Comment by ESP32DE** [comment]
empty promises .-
Pity about the wasted time
Will use my time now more meaningfully

**Comment by xcguang** [comment]
@ESP32DE 
Hi Rudy,
We have fixed it,Please try it again, thanks.
