### ISSUE TITLE
wifi: esp_wifi_set_storage 1231 wifi is not init

### ISSUE THREAD

**Issue by gokr** [espressif/esp32-at#10]
I would like https://github.com/espressif/esp32-at/issues/6 to be read and reopened since it is NOT solved at all. That issue was closed out of irritation. Please try to compile and run this firmware with the latest esp-idf and fix the bug.

**Comment by xcguang** [comment]
Hi @gokr ,
We have fix it,please try it again.If you have any problem,please feel free to let us know.Thanks.

**Comment by gokr** [comment]
Ok, I will try it, great!

**Comment by gokr** [comment]
Ok, now I have tested this and... well, yes, now it works but I have two other problems. First of all, in order to get "ready" I had to make the changes for the UART described here:

https://www.esp32.com/viewtopic.php?f=2&t=1103&hilit=AT+commands&start=40

...then when I do it all and "make monitor" it shows everything up to "ready" but when I type in "AT" etc it doesn't answer anything back.

However, if I then switch IDF_PATH to the old 2.0-rc1 - then it works just fine. So I am guessing something is off with "make monitor" in the submodule esp-idf?

**Comment by ESP32DE** [comment]
@gokr
you do not need to switch back to older IDF for run "monitor" 
 
if you use the actually IDF
monitor goes to simple_monitor
and the new monitor now is new

you can use
**make simple_monitor**
cause monitor is new and do just in time not support CR LF after send the command.
https://github.com/espressif/esp-idf/commit/02fdf8271de3a6db2ab9d4d6f023c160c84ebdbe
( scroll down to the comments ) 


@xcguang
AT Example now it runs like it must. thank you

best wishes
rudi ;-)


> $ make monitor
> MONITOR
> --- idf_monitor on COM27 115200 ---
> --- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> ets Jun 8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> ets Jun 8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3464
> load:0x40078000,len:7828
> load:0x40080000,len:252
> 0x40080000: _WindowOverflow4 at ??:?
> entry 0x40080034
> 0x40080034: _WindowOverflow4 at ??:?
> I (43) boot: ESP-IDF v2.0-rc1-296-g02fdf82 2nd stage bootloader
> I (44) boot: compile time 16:13:37
> I (44) boot: Enabling RNG early entropy source...
> I (64) boot: SPI Speed : 40MHz
> I (77) boot: SPI Mode : DIO
> I (89) boot: SPI Flash Size : 4MB
> I (101) boot: Partition Table:
> I (113) boot: ## Label Usage Type ST Offset Length
> I (135) boot: 0 phy_init RF data 01 01 0000f000 00001000
> I (159) boot: 1 ota_0 OTA app 00 10 00010000 000ea000
> I (182) boot: 2 nvs WiFi data 01 02 000fa000 00016000
> I (205) boot: 3 ota_1 OTA app 00 11 00110000 000ea000
> I (228) boot: 4 otadata OTA data 01 00 001fd000 00003000
> I (252) boot: End of partition table
> I (265) boot: Disabling RNG early entropy source...
> I (282) boot: Loading app partition at offset 00010000
> I (1450) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512)
> I (1450) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x19e78 (106104) map
> I (1467) boot: segment 2: paddr=0x00039e88 vaddr=0x3ffb0000 size=0x02190 ( 8592) load
> I (1497) boot: segment 3: paddr=0x0003c020 vaddr=0x40080000 size=0x00400 ( 1024) load
> 0x40080000: _WindowOverflow4 at ??:?
> I (1520) boot: segment 4: paddr=0x0003c428 vaddr=0x40080400 size=0x1a70c (108300) load
> I (1598) boot: segment 5: paddr=0x00056b3c vaddr=0x400c0000 size=0x00034 ( 52) load
> I (1599) boot: segment 6: paddr=0x00056b78 vaddr=0x00000000 size=0x09490 ( 38032)
> I (1615) boot: segment 7: paddr=0x00060010 vaddr=0x400d0018 size=0x78f08 (495368) map
> 0x400d0018: _stext at ??:?
> I (1642) cpu_start: Pro cpu up.
> I (1653) cpu_start: Single core mode
> I (1667) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
> I (1690) heap_alloc_caps: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM
> I (1711) heap_alloc_caps: At 3FFBA6B0 len 00025950 (150 KiB): DRAM
> I (1732) heap_alloc_caps: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
> I (1753) heap_alloc_caps: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
> I (1775) heap_alloc_caps: At 4009AB0C len 000054F4 (21 KiB): IRAM
> I (1796) cpu_start: Pro cpu start user code
> [0;32}I (1856) cpu_start: Starting scheduler on PRO CPU.
> 
> eMbeddedHome 2017
> I (1868) uart: queue free spaces: 10
> I (1906) wifi: wifi firmware version: 0b5b6e7
> I (1906) wifi: config NVS flash: enabled
> I (1906) wifi: config nano formating: disabled
> I (1911) wifi: Init dynamic tx buffer num: 32
> I (1912) wifi: wifi driver task: 3ffc3060, prio:23, stack:3584
> I (1917) wifi: Init static rx buffer num: 10
> I (1921) wifi: Init dynamic rx buffer num: 0
> I (1925) wifi: Init rx ampdu len mblock:7
> I (1928) wifi: Init lldesc rx ampdu entry mblock:4
> I (1933) wifi: wifi power manager task: 0x3ffc8408 prio: 21 stack: 2560
> I (1939) wifi: wifi timer task: 3ffc9488, prio:22, stack:3584
> E (1945) phy_init: PHY data partition validated
> I (1968) phy: phy_version: 329, Feb 22 2017, 15:58:07, 0, 0
> I (1969) wifi: Init ampdu: 1
> I (1969) wifi: Init ampdu: 1
> I (1969) wifi: mode : sta (24:0a:c4:04:5c:8c) + softAP (24:0a:c4:04:5c:8d)
>   
> ready
>   
> --- idf_monitor (1.0) - ESP-IDF monitor tool
> --- based on miniterm from pySerial
> ---
> --- Ctrl+] Exit program
> --- Ctrl+T Menu escape key, followed by:
> --- Menu keys:
> --- Ctrl+T Send the menu character itself to remote
> --- Ctrl+] Send the exit character itself to remote
> --- Ctrl+R Reset target board via RTS line
> --- Ctrl+F Run 'make flash' to build & flash
> --- Ctrl+A Run 'make app-flash to build & flash app
> 
> 
> 


simple_monitor


> $ make simple_monitor
> --- forcing DTR inactive
> --- forcing RTS inactive
> --- Miniterm on COM27  115200,8,N,1 ---
> --- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3464
> load:0x40078000,len:7828
> load:0x40080000,len:252
> entry 0x40080034
> [0;32mI (44) boot: ESP-IDF v2.0-rc1-296-g02fdf82 2nd stage bootloader[0m
> [0;32mI (44) boot: compile time 16:13:37[0m
> [0;32mI (45) boot: Enabling RNG early entropy source...[0m
> [0;32mI (65) boot: SPI Speed      : 40MHz[0m
> [0;32mI (78) boot: SPI Mode       : DIO[0m
> [0;32mI (90) boot: SPI Flash Size : 4MB[0m
> [0;32mI (102) boot: Partition Table:[0m
> [0;32mI (114) boot: ## Label            Usage          Type ST Offset   Length[0m
> [0;32mI (136) boot:  0 phy_init         RF data          01 01 0000f000 00001000[0m
> [0;32mI (160) boot:  1 ota_0            OTA app          00 10 00010000 000ea000[0m
> [0;32mI (183) boot:  2 nvs              WiFi data        01 02 000fa000 00016000[0m
> [0;32mI (206) boot:  3 ota_1            OTA app          00 11 00110000 000ea000[0m
> [0;32mI (229) boot:  4 otadata          OTA data         01 00 001fd000 00003000[0m
> [0;32mI (253) boot: End of partition table[0m
> [0;32mI (266) boot: Disabling RNG early entropy source...[0m
> [0;32mI (283) boot: Loading app partition at offset 00010000[0m
> [0;32mI (1450) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512) [0m
> [0;32mI (1451) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x19e78 (106104) map[0m
> [0;32mI (1468) boot: segment 2: paddr=0x00039e88 vaddr=0x3ffb0000 size=0x02190 (  8592) load[0m
> [0;32mI (1498) boot: segment 3: paddr=0x0003c020 vaddr=0x40080000 size=0x00400 (  1024) load[0m
> [0;32mI (1521) boot: segment 4: paddr=0x0003c428 vaddr=0x40080400 size=0x1a70c (108300) load[0m
> [0;32mI (1599) boot: segment 5: paddr=0x00056b3c vaddr=0x400c0000 size=0x00034 (    52) load[0m
> [0;32mI (1600) boot: segment 6: paddr=0x00056b78 vaddr=0x00000000 size=0x09490 ( 38032) [0m
> [0;32mI (1616) boot: segment 7: paddr=0x00060010 vaddr=0x400d0018 size=0x78f08 (495368) map[0m
> [0;32mI (1643) cpu_start: Pro cpu up.[0m
> [0;32mI (1654) cpu_start: Single core mode[0m
> [0;32mI (1668) heap_alloc_caps: Initializing. RAM available for dynamic allocation:[0m
> [0;32mI (1691) heap_alloc_caps: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM[0m
> [0;32mI (1712) heap_alloc_caps: At 3FFBA6B0 len 00025950 (150 KiB): DRAM[0m
> [0;32mI (1733) heap_alloc_caps: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
> [0;32mI (1754) heap_alloc_caps: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
> [0;32mI (1776) heap_alloc_caps: At 4009AB0C len 000054F4 (21 KiB): IRAM[0m
> [0;32mI (1796) cpu_start: Pro cpu start user code[0m
> [0;32}I (1857) cpu_start: Starting scheduler on PRO CPU.[0m
> 
> eMbeddedHome 2017
> [0;32mI (1869) uart: queue free spaces: 10[0m
> I (1907) wifi: wifi firmware version: 0b5b6e7
> I (1907) wifi: config NVS flash: enabled
> I (1907) wifi: config nano formating: disabled
> I (1912) wifi: Init dynamic tx buffer num: 32
> I (1913) wifi: wifi driver task: 3ffc3060, prio:23, stack:3584
> I (1918) wifi: Init static rx buffer num: 10
> I (1922) wifi: Init dynamic rx buffer num: 0
> I (1926) wifi: Init rx ampdu len mblock:7
> I (1929) wifi: Init lldesc rx ampdu entry mblock:4
> I (1934) wifi: wifi power manager task: 0x3ffc8408 prio: 21 stack: 2560
> I (1941) wifi: wifi timer task: 3ffc9488, prio:22, stack:3584
> [0;31mE (1946) phy_init: PHY data partition validated[0m
> [0;32mI (1969) phy: phy_version: 329, Feb 22 2017, 15:58:07, 0, 0[0m
> I (1970) wifi: Init ampdu: 1
> I (1970) wifi: Init ampdu: 1
> I (1970) wifi: mode : sta (24:0a:c4:04:5c:8c) + softAP (24:0a:c4:04:5c:8d)
> 
> ready
> AT+GMR
> AT version:0.10.0.0(Mar 16 2017 19:02:43)
> SDK version:v2.0-rc1-296-g02fdf82
> compile time:Mar 17 2017 13:03:48
> OK

**Comment by gokr** [comment]
Works
