### ISSUE TITLE
AT+UART_DEF不動作

### ISSUE THREAD

**Issue by ttnjkoft** [espressif/esp32-at#102]
您好，最近在做ESP32的實驗，我使用AT+UART_DEF改變baudrate到460800，當下改變了，但我重置ESP32後baudrate又變回預設的115200，請問有什麼方式可以變更baudrate成預設值呢?

**Comment by xcguang** [comment]
您可以通过`make menuconfig` 来设置 ，`Component config` --> `AT` --> `AT uart setting`

**Comment by xcguang** [comment]
Hi，
请问一下，这个问题解决了吗？
我将先关闭这个 issue，如果问题依旧，请重新打开，谢谢！
