### ISSUE TITLE
Irregular TCP connection is closed

### ISSUE THREAD

**Issue by zjykymt** [espressif/esp32-at#106]
I tested the stability of the ESP32 connection TCP, and then often the situation that TCP was closed.
I enabled the TCP keep-alive function and the detection time is 10s.

AT version:1.1.0.0(e83e1f4 - Jun  1 2018 07:10:27) 
SDK version:v3.0.1-rc
compile time:Jun 11 2018 12:42:49 
Bin version(Wroom32):1.1.0 

# Log duration for each TCP connection
![image](https://user-images.githubusercontent.com/9928032/41825907-bc506c68-7857-11e8-8950-4cb9dab164cd.png)

# ESP32 Tx pin monitoring log
![image](https://user-images.githubusercontent.com/9928032/41825917-f5eb8d68-7857-11e8-8c68-ac11f20953f2.png)

# My application log
![image](https://user-images.githubusercontent.com/9928032/41825929-0325243a-7858-11e8-9c91-9749fba70ceb.png)

**Comment by xcguang** [comment]
Hi, 
Could you provide some packets? for example, the WiFi packets captured by the omnipeek or the ethernet packets of the server by the wireshark?

**Comment by zjykymt** [comment]
Currently I can't capture this type of packet here, I will close this ISSUE first, if I confirm the problem will open.

**Comment by zjykymt** [comment]
Hi,

At present, we have decided to put the ESP32 module into production, but this problem still exists. This problem makes my team feel not very stable.

What I want to know is how many cases ESP32 modules will send 0, CLOSE.

AT version is 1.1.2.0

Thanks.

**Comment by xcguang** [comment]
Could you provide some packets? for example, the WiFi packets captured by the omnipeek or the ethernet packets of the server by the wireshark?

**Comment by zjykymt** [comment]
I am using wireshark to capture the package.
Once this happens, I will upload the packet capture data.

**Comment by zjykymt** [comment]
![image](https://user-images.githubusercontent.com/9928032/45203630-58954a80-b2af-11e8-8497-0bd75a240256.png)

Hi, this is one of the cases, I will always monitor for more packet capture data.

**Comment by zjykymt** [comment]
![image](https://user-images.githubusercontent.com/9928032/45205660-5df59380-b2b5-11e8-8ea2-86d566f33e10.png)
![image](https://user-images.githubusercontent.com/9928032/45205679-68b02880-b2b5-11e8-86a6-8ffacf69b555.png)

This is the other two TCP disconnected packet capture data.

**Comment by zjykymt** [comment]
Hi,

It seems that the client is actively resetting TCP.
Can these data help determine the cause?

**Comment by xcguang** [comment]
I guess it maybe ESP32 does not receive the packet from the air for a long time, or ESP32 sends data to the server because of the server does not receive them, then ESP32 closes the socket. When receiving the data again,  ESP32 will reset the peer because the socket has been closed.
