### ISSUE TITLE
"busy p..." causes module to crash

### ISSUE THREAD

**Issue by zjykymt** [espressif/esp32-at#109]
Hi,
I tried to send the two commands "ATE0" and "AT+GMR" consecutively after receiving "ready", and "busy p..." appears , after the module will always be in the state of sending "busy p..."

Version:
AT version:1.1.0.0(e83e1f4 - Jun  1 2018 07:10:27)
SDK version:v3.0.1-rc
compile time:Jun 11 2018 12:42:49
Bin version(Wroom32):1.1.0

![image](https://user-images.githubusercontent.com/9928032/42443824-25fa9f7c-83a1-11e8-84aa-bc0f9139340c.png)

**Comment by xcguang** [comment]
Please try the latest release/v1.1.0.0.  We have fix it.
https://github.com/espressif/esp32-at/commits/release/v1.1.0.0

**Comment by zjykymt** [comment]
The latest release/V1.1.1.0 have fixed it. 

Thanks.
