### ISSUE TITLE
Gatt service example, more example

### ISSUE THREAD

**Issue by JTrotta** [espressif/esp32-at#114]
May you add more example like GattServiceExample.csv? With read, write and notify in the same characteristic, with write no response, etc. etc?
Thank you.

**Comment by xcguang** [comment]
Hi @JTrotta ，
Thanks for your advice, and we will add them in example.

**Comment by JTrotta** [comment]
Great! I'm having problems in configuring one characteristic, with read write and notify. In some tests read works and write not, in some others viceversa.
Many thanks.

**Comment by xiewenxiang** [comment]
Hi @JTrotta 
[example.csv.tar.gz](https://github.com/espressif/esp32-at/files/2270849/example.csv.tar.gz)
