### ISSUE TITLE
AT+BLEGATTSSRV returns error after OTA update to 1.1.1

### ISSUE THREAD

**Issue by cwq9999** [espressif/esp32-at#115]
Previously I have been able to run the following command set on the AT v1.0 firmware without any changes to the stock firmware.

AT+BLEINIT=2

AT+BLEGATTSSRVCRE

AT+BLEGATTSSRVSTART

AT+BLEADVSTART

However now that I upgraded my ESP32 to v1.1.1 via OTA using the following commands:

AT+CWMODE=1

AT+CWJAP=“SSID”,”PW” 

AT+CIPDOMAIN="iot.espressif.cn"

AT+CIUPDATE

When I enter:
AT+BLEGATTSSRVCRE

I get an error. My guess is that the generic GATT services are no longer present. How can I update the GATT service?

**Comment by xcguang** [comment]
Hi,
 After `AT+CIUPDATE`, it will reboot, so you need enter `AT+BLEINIT=2` again.
