### ISSUE TITLE
GATT Service Bin files and update via AT+SYSFLASH?

### ISSUE THREAD

**Issue by cwq9999** [espressif/esp32-at#118]
Where on the flash memory are the files for the GATT service and Tools stored on the ESP32 flash? Can those files be updated via AT+SYSFLASH or can these only be added after compiling the full image and flashing using make flash commands and the primary RX/TX pins rather than using the AT RX/TX pins?

**Comment by alexdecei** [comment]
Hello, is there any changes about that topic ?
