### ISSUE TITLE
Please include LICENSE file

### ISSUE THREAD

**Issue by beriberikix** [espressif/esp32-at#119]
Under what license is this project released under? Is it the same as the `esp-idf`, Apache 2? If so, can you please include the appropriate `LICENSE` file in the root directory.

Thanks!

**Comment by xcguang** [comment]
Hi @beriberikix , 
Sorry for the confusion, we will add it ASAP.

**Comment by beriberikix** [comment]
Thank you @xcguang! Can you please also add the appropriate license or terms of use for the AT binary itself?

**Comment by beriberikix** [comment]
Any updates?

**Comment by beriberikix** [comment]
45fcf1b fixes this. Thanks @xiewenxiang!
