### ISSUE TITLE
+NOTIFY <value> is string?

### ISSUE THREAD

**Issue by squallwc12** [espressif/esp32-at#125]
used frimware is V1.0.0
+NOTIFY:0,3,2,8,?
? is <value>, Hexadecimal 0xAB. The complete data should be :0xAB 0x00 0x05 0x00 0x91 0x80 0x01 0x64
buy I only receive 1 byte: 0xAB
I think <value> used string format output, 0x00 is the end of string sign ,so i only receive 0xAB.
+NOTIFY:,,,,<value> Can output hex format or other format？What should I do.
----------
AT+GMR
AT version:1.0.b1.0(1e9060d - Jan 22 2018 17:39:07)
SDK version:v2.1
compile time:Jan 22 2018 17:41:13
OK

thank you

**Comment by xcguang** [comment]
yes, it's hex string.
