### ISSUE TITLE
Eclipse error *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by VictorDuma** [espressif/esp32-at#126]
When I try to compile esp32-at example with the Eclpipse on Win10 I got error /home/mypc/esp/esp-idf/make/component_wrapper.mk:285: *** target pattern contains no '%'.  Stop.
All variables was set according the documentation. Same time I was able to compile with the console. Looks like some conflict with windows style path and unix style. What can I check else?

**Comment by rochamorelli** [comment]
I had the same problem when cloning a pre-built repo. Maybe it's not the same problem you have, but I managed to solve it by erasing the `build` folder.

**Comment by Ralim** [comment]
Confirming that a `rm -rf` of build worked for me as well.
Issue showed up when moving to WSL from the MYSYS and obviously had old paths cached in the build folder somewhere.
