### ISSUE TITLE
AT-Firmware and WiFi/Bluetooth classic protocols

### ISSUE THREAD

**Issue by tchouzin** [espressif/esp32-at#129]
Hello  @xcguang 

I would like to know if the AT-Firmware supports WiFi and Bluetooth classic protocols at the same time? That is, can we run both at the same time? 
I get an error when Wi-Fi is connected and I try to connect the Bluetooth classic.

Regards,

Achille

**Comment by xcguang** [comment]
Hi，
If you want to run WiFi and Bluetooth classic protocols, you need a param, because there is no enough ram.

**Comment by tchouzin** [comment]
Hello @xcguang ,
What do you mean by  * param?

**Comment by xcguang** [comment]
Hi,
"param" is external RAM. Please refer to the document about ESP32-WROVER module at https://www.espressif.com/en/support/download/documents.

**Comment by xcguang** [comment]
Hi,
I will close the issue, if you have any question, please reopen it again or create a new issue.
