### ISSUE TITLE
Classic Bluetooth Initialization Error

### ISSUE THREAD

**Issue by Arti4ever** [espressif/esp32-at#130]
Hello, 
I've got an Espressif ESP32-WROVER-B module which is supposed to have external ram to handle wifi/BT/BLE.
I configured the esp32-at firmware to have wifi and BT support with the lastest souces available so far (commit 1a14b55). 

When I try to initialize the classic Bluetooth the module return an error :
AT+BTINIT=1
ERROR

I try disabling the ble at support as said in Issue #110 but this did not work for me.

Can you tell me what I missed ?

Regards.

**Comment by Arti4ever** [comment]
Hi, 
In fact, since the lastest commit 1a14b55, classic bleutooth do not work anymore. 

I've tested with commit 036e3556 and bluetooth initialization worked. 
But AT+BTSTARTDISC return wrong name and sometimes bad characteres. 
and AT+BTSPP is not working...

**Comment by xcguang** [comment]
Hi,
Did you configure `Component config > AT > [*]   AT bt command support. `

**Comment by Arti4ever** [comment]
Hi,
Yes I did.
Did you test classic Bluetooth with the lastest commit ?

**Comment by xcguang** [comment]
Hi,
Please try it again using the latest master branch.
BTW, you need configure `Component config > Bluetooth > Bluetooth controller > (X) Bluetooth Dual Mode`

**Comment by Arti4ever** [comment]
Hi, 
Thanks, Initialization works now. 
But this is the only things that works. I will open new issues to be more clear.
