### ISSUE TITLE
[ESP32AT-163] Classic Bluetooth set and get Name Error.

### ISSUE THREAD

**Issue by Arti4ever** [espressif/esp32-at#134]
Hi,
I'va got an ESP32_Wrover with External RAM enabled.
Classic bluetooth set and get name (AT+BTNAME) do not work. 

Get name return empty string :
AT+BTNAME?
+BTNAME:
OK

and set name return an error:
AT+BTNAME="Test"
ERROR

**Comment by xiewenxiang** [comment]
Hi @Arti4ever 
Do you have Initialized the BT stack before set the name?

**Comment by Arti4ever** [comment]
Hi @xiewenxiang, 
Yes BT stack was enabled with BTINIT=1.

**Comment by Arti4ever** [comment]
any update ?

**Comment by Arti4ever** [comment]
up

**Comment by xiewenxiang** [comment]
@Arti4ever 
Please pull the latest master branch
