### ISSUE TITLE
Classic Bluetooth SPP init error

### ISSUE THREAD

**Issue by Arti4ever** [espressif/esp32-at#135]
Hi,
I'va got an ESP32_Wrover with External RAM enabled.
Classic bluetooth SPP initialization  (AT+BTSPP) do not work.

AT+BTSPP?
ERR CODE:0x01090000
ERROR

Seems like SPP is not enable despite I enabled it in the menuconfig.

**Comment by xiewenxiang** [comment]
Hi @Arti4ever 

In the document, this command description was wrong，please use `AT+BTSPPINIT?`, we will fix it ASAP.

**Comment by Arti4ever** [comment]
Hi @xiewenxiang,
Thank you for the advice !

Issue Closed.
