### ISSUE TITLE
[ESP32AT-162] Classic Bluetooth Scan not working correctly

### ISSUE THREAD

**Issue by Arti4ever** [espressif/esp32-at#136]
Hi,
I'va got an ESP32_Wrover with External RAM enabled.
Classic bluetooth scan (AT+BTSTARTDISC) do not work correctly.

Endeed, sometimes wrong characteres are send to the uart. 
For instance: 
+BTSTARTDISC:98:9c:57:82:a9:2c,øÿÿ?EI P8 lite 2017,-73,2,0x2d0
We see that there are somme characteres "øÿÿ?" who should not be here. 
the real name of the device is "HUAWEI P8 lite 2017"

An other issue is that the name buffer is not clear between two messages.
For exemple, I get this:
+BTSTARTDISC:00:06:66:77:7e:ca,øÿÿ?EI P8 lite 2017,-48<CR><LF>
+BTSTARTDISC:00:06:66:77:7e:ca,PRECIA_i5-7ECA 2017,-43<CR><LF>
=> the "2017" should not be here for the "PRECIA_i5-7ECA" device. It seems it comes from the previous device "HUAWEI P8 lite 2017"

And an other issue is that MAC address do not always match the device name... 
In the previous exemple, both devices have the same MAC address but in fact HUAWEI have "98:9c:57:82:a9:2c" and "PRECIA_i5-7ECA" have "00:06:66:77:7e:ca"

So there is many many bugs in bluetooth scanning.

**Comment by Arti4ever** [comment]
Did you find something ?

**Comment by Arti4ever** [comment]
up

**Comment by xiewenxiang** [comment]
@Arti4ever 
Please pull the latest master branch
