### ISSUE TITLE
[ESP32AT-171] AT+BLEGATTSNTFY error on the gatt server side (MTU management)

### ISSUE THREAD

**Issue by mrbiondo** [espressif/esp32-at#148]
A Gatt server manages 2 connections with 2 different Gatt clients.
Every Gatt client negotiates its MTU.
When a Gatt client disconnects, the MTU of the other connection resets to 20 bytes, but only on the Gatt server side.

The version information is:
AT version:1.2.0.0-dev(6e68431 - Sep 21 2018 09:16:33)
SDK version:v3.1-34-gcea4d3132

Following are the steps to replay the error.

On the Gatt server side 
First connection 
+BLECFGMTU:0,128

Second connection
+BLECFGMTU:1,517

The query command gives
AT+BLECFGMTU?
+BLECFGMTU:0,128
+BLECFGMTU:1,517

Gatt clients/sever can write/notify data up to their negotiated MTU bytes.
After a client disconnection the query command gives
AT+BLECFGMTU?
+BLECFGMTU:0,128

The Gatt server cannot accept this command
AT+BLEGATTSNTFY=0,1,2,64
ERROR

Instead, the Gatt server can do this one
AT+BLEGATTSNTFY=0,1,2,20
>xxxxxxxxxxxxxxxxxxxx
OK

From the Gatt client it is still possible to receive write event like the following
+WRITE:0,1,2,,64,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Could anyone help me, please?

**Comment by xiewenxiang** [comment]
@mrbiondo 

Thanks for you informations, we will fix it.

**Comment by mrbiondo** [comment]
I look forward to that fix  as I really need that feature. As you see, at the moment the workaround is notifyng with the minimum mtu. Thanks.

**Comment by xiewenxiang** [comment]
We have fixed it, Please pull the latest master branch.
