### ISSUE TITLE
Max link ID

### ISSUE THREAD

**Issue by Zdeno5** [espressif/esp32-at#152]
Hi. 

Is there a way to increase max connection on TCP  server to 10? (0-9 link ID)

**Comment by xcguang** [comment]
You can set it by calling `esp_at_module_init`, and then compile the binary

**Comment by kurta999** [comment]
On WROVER, where 8/16MB PSRAM is present, can it be increased to 20 or even 30/40?

**Comment by xcguang** [comment]
It depends on your application scenario. Such as enabling Bluetooth? Enabling SSL?  Or enable other functions. Suggest you do a test.

**Comment by xcguang** [comment]
By the way, maybe you need to configure socket number in `make menuconfig`
