### ISSUE TITLE
AT+GMR: Add Custom Info

### ISSUE THREAD

**Issue by carlessole** [espressif/esp32-at#158]
Hi,
When using ESP8266 there is a function to add custom info to the command: AT+GMR:

```
/**
  * @brief  print custom information when AT+GMR
  * @param  string
  * @retval None
  */
void at_set_custom_info(char* info);
```
I'm not able to find how to do that with ESP32.
Is there any way to do that?

Thanks.

**Comment by xiewenxiang** [comment]
```c
void esp_at_module_init (uint32_t netconn_max, const uint8_t *custom_version);
```

This API was used to set the customer version.

**Comment by carlessole** [comment]
Thanks @xiewenxiang !
It has worked fine!
