### ISSUE TITLE
BLE initialization problem

### ISSUE THREAD

**Issue by kmakhil90** [espressif/esp32-at#160]
It is giving error when try BLE init as AT+BLEINIT=1/2.

**Comment by xiewenxiang** [comment]
Please provide the version you are using now
`AT+GMR`

**Comment by xiewenxiang** [comment]
It may be because you've enable the classic bluetooth command, but the bluetooth configuration is still single-mode

**Comment by kmakhil90** [comment]
> It may be because you've enable the classic bluetooth command, but the bluetooth configuration is still single-mode

It may be correct, let me see.

**Comment by kmakhil90** [comment]
> > It may be because you've enable the classic bluetooth command, but the bluetooth configuration is still single-mode
> 
> It may be correct, let me see.

Thanks. Solved this by disabling the classic bluetooth in module.
