### ISSUE TITLE
AT+CIPMODE=1 ..stop sending data with +++ proposal response_ok

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-at#2]
hi
proposal:
if we stop sending data with '+++' in transparent mode ( AT+CIPMODE=1 ) 
there comes just in time no "OK\r\n"

if we can check for an "OK\r\n" 
we do not need wait "1 second" and try for next AT Command
we can check after sending stop signal ( +++ ) for an "OK\r\n" and 
then we can use next AT Command without a "wait"

![8](https://cloud.githubusercontent.com/assets/16070445/22813051/f56d9596-ef48-11e6-9924-49b9ad630e5b.png)

cause AT is in a LIB
can't link and pull request the code for it 
hope the proposal is understandly written.

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
No interest - ok
have done in my repo
Close it

**Comment by xcguang** [comment]
Thank you very much for your advice.We'll consider it,but it needs take some time to do with it.

**Comment by ESP32DE** [comment]
you dont want this help and support
be happy with your AT example
we take other manufacturer in future 
for this.
