### ISSUE TITLE
Is passive mode TCP receive planned for ESP32 in near future?

### ISSUE THREAD

**Issue by kurta999** [espressif/esp32-at#208]
Hi,

Is passive mode planned for TCP in the future for ESP32, it is already present in ESP8266? It would save plenty of time four our company. ESP with AT has a few MB of free ram, so this option would allow MCUs to decide when to receive data from wifi and how many at a time without data being lost.

**Comment by xiewenxiang** [comment]
Master branches already support this feature.

**Comment by xiewenxiang** [comment]
If you have any questions, you can re-open this issue.
