### ISSUE TITLE
Add "at_customize.bin" and "service bin" directly from the ESP32

### ISSUE THREAD

**Issue by alexdecei** [espressif/esp32-at#210]
Hello,
Is there any way to flash the ESP32 and add "GATT Service Bin" without a computer ?
Only with the ESP32, a wifi connection and AT commands ?

I need to set up a ble server without programing the ESP, only with AT commands.

Thank you.

**Comment by xiewenxiang** [comment]
This feature is not currently supported.

**Comment by alexdecei** [comment]
Hi, do you mean that you do not handle "GATT service bin" issues ? Or that there is no solution for that problem ?

Thanks

**Comment by xiewenxiang** [comment]
At present, only support download tools, don't support other ways.

**Comment by alexdecei** [comment]
All right thanks.
