### ISSUE TITLE
Connected flags?

### ISSUE THREAD

**Issue by jitenshap** [espressif/esp32-at#220]
I trying write custom AT Wi-Fi command for power saving.
When disabling AT wifi command support and using my AT Wi-Fi command, net commands does'nt works.(I received "no ip" from debug console)

Does the net command need some Wi-Fi connected flags?

**Comment by SONGjiaxiu** [comment]
Hi,
The net command is based on AT Wi-Fi command in the common AT project,  if you want to use net command, you must  enable AT wifi command. 
You can enable wifi command, and just implement your wifi commands, then send your wifi command. BTW, please donot regist callback about wifi event.

**Comment by jitenshap** [comment]
Thank you for response.
I must write also net command for power saving.
When I regist a Wi-Fi command, ESP32 uses 100 mA even if CWMODE = 0.
