### ISSUE TITLE
Specify connections for server

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp32-at#28]
When device is in server mode, it can happen that at some point, all connections are used for server and there is no support to use client mode at that time.

What we should have option to set is which connections are available for server.

Correct me if I'm mistaken, but current server approach is like this:

- User enables server at specific port
- ESP creates new connection and listens at specific port
- When connection is accepted, ESP creates new empty connection to listen on same port
- And so on, which means there is always one connection active and ready to accept new connection, except if we reached max connections.

We should be able to limit the number of connections and for example only allow server to use them:

- uC sends `AT+CIPSERVERCONN=1,0,80`
- uC sends `AT+CIPSERVERCONN=1,1,90`
- uC sends `AT+CIPSERVERCONN=1,2,100`

These 3 commands would enable connections `0,1,2` only for server at ports `80`, `90`, `100`. If ESP got more than 3 connections at a time, they should wait before one of these 3 is available again. LwIP does support multiple ports where it accepts the connection so this should be able also here with AT.

If we then try `AT+CIPSTART=1,...` from uC, we should got an error because connection is reserved for server only! In this case, we can use connections `4,5` for client.

---
This allows us to have better control from uC, specially on devices with small amount of RAM.
On top of RAM control, it also allows you to prepare MCU, just like ESP prepares with LwIP stack which connections and callbacks are used before actual data are ready.

I'm waiting for your response!

**Comment by xcguang** [comment]
Hi @MaJerle ,
Your opinion is a very good suggestion，and we will consider it in the next release.
Thanks very much.

**Comment by MaJerle** [comment]
Hello @xcguang,

That's good to hear. I will post the same issue request to ESP8266 AT repository.
