### ISSUE TITLE
register server callback for act on received client data

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-at#3]
hi

how we can create/register the server callback for act on client request/received data?
we get 

+IPD,0,n:xxxxxxxxxx		//	received	n	bytes,	data	=	xxxxxxxxxx
 
now we need a callback for act.

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
No interest - ok
have done in my PC Repo
Close it

**Comment by xcguang** [comment]
Thanks for your interest in esp32-at. Now there isn't server callback for  client request/received data in libat-core.a. Maybe you could parse "+IPD" in at_port_write_data,then do what you want to do.

**Comment by ESP32DE** [comment]
> Maybe you could parse "+IPD" in at_port_write_data

thank you for your response.
yes this is the thing i do just in time 
( did in esp8266 too after the src was gone to lib )
https://youtu.be/WFo4Fs0p_NY?t=84

comfortable as parse would be,
can we use isr notify and  
can we use pointer to pvParameters / request data

the thing with "parse" is not professional :)
but ok for the most things to do as at processor with connected second µC ( microcontroller ) 

thank you 
best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
you do not want this help
so be happy....
