### ISSUE TITLE
Guru Meditation Error while performing SSL handshake

### ISSUE THREAD

**Issue by salqadri** [espressif/esp32-at#31]
While I am trying to connect to an SSL server, I am consistently getting the following crash:
[I][ssl_client.cpp] start_ssl_client(): Free heap before TLS 149404
[I][ssl_client.cpp] start_ssl_client(): Starting socket
[I][ssl_client.cpp] start_ssl_client(): Seeding the random number generator
[I][ssl_client.cpp] start_ssl_client(): Setting up the SSL/TLS structure...
[I][ssl_client.cpp] start_ssl_client(): Loading CA cert
[I][ssl_client.cpp] start_ssl_client(): Performing the SSL/TLS handshake...
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU1)
Register dump:
PC      : 0x400e6a40  PS      : 0x00060934  A0      : 0x8008597c  A1      : 0x3ffcc5a0  
A2      : 0x00000008  A3      : 0x00000001  A4      : 0x00060023  A5      : 0x3ffcccfc  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x3ffc3a64  A9      : 0x3ffcc580  
A10     : 0x00000000  A11     : 0x00060920  A12     : 0x80084458  A13     : 0x3ffcc4a0  
A14     : 0x00000000  A15     : 0x3ffcc120  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x400e6a40:0x3ffcc5a0 0x4008597c:0x3ffcc5c0

Any ideas on what might be happening?

**Comment by xcguang** [comment]
Maybe it takes too long time to shake hands for encryption and decryption.
