### ISSUE TITLE
libat_core.a and ESP-IDF V2.1

### ISSUE THREAD

**Issue by santanapablo1975** [espressif/esp32-at#34]
Hi All

I would like to ask who to integrate the libat_core.a to the latest release of the ESP-IDF v2.1
Looks like according to the docs here that at the moment it is co-related to a specific ESP-IDF version.

I would like to request some advice about how to integrate the the libat_core.a to the new ESP-IDF realese?
Thanks

Juan

**Comment by mxwang101** [comment]
Same problem. 
I do try it, but the program keep reboot, not work. switch back to ESP-IDF und esp32-at, work fine.

**Comment by xcguang** [comment]
Hi, now libat_core.a is compiled based on the latest release of the ESP-IDF v2.1. What's the problem with you? Please feel free to let me know,thanks.

**Comment by santanapablo1975** [comment]
Hi All, I get the following error:

E (1947) wifi: invalid magic number 0, call WIFI_INIT_CONFIG_DEFAULT to init config
E (1947) wifi: wifi_init 1346 ret=258
ESP_ERROR_CHECK failed: esp_err_t 0x102 at 0x4011f7ab

Backtrace: 0x40088710:0x3ffb4770 0x40088a7d:0x3ffb4790 0x4011f7ab:0x3ffb47b0 0x4012006b:0x3ffb4800 0x40102b4b:0x3ffb4840 0x4010252f:0x3ffb4880 0x400d0d06:0x3ffb48a0

Rebooting...

here the complete log as attached file "putty.txt"

I had switsched to the previous release v2.0 and it works fine... in addition "mxwanf101" report the same problem

Any advice or tip according the log file?
[putty.txt](https://github.com/espressif/esp32-at/files/1211462/putty.txt)

**Comment by santanapablo1975** [comment]
Hi All gain, in the previous log I compiled with a debug version and that was the error reason

`[0;32mI (30) boot: ESP-IDF v3.0-dev-241-g1c6be3a 2nd stage bootloader[0m`

Now I recompiled with the right version:

and the problem is gone!
I (32) boot: ESP-IDF v2.1 2nd stage bootloader

We can close this issue!


Thanks in any case!

Regards!

Juan

**Comment by mxwang101** [comment]
Cloud you please let us know how to get "the right version"? Thanks

**Comment by santanapablo1975** [comment]
Hi mxwang101

please follow the instructions at the end of this link

https://github.com/espressif/esp32-at

please let us know how does it works!

regards

Juan
