### ISSUE TITLE
esp32-at make flash error

### ISSUE THREAD

**Issue by klteng** [espressif/esp32-at#39]
When I execute the "make flash", I always got the error....why?  I followed all the instruction given in the readme.md file.

$ make flash
CC src/bootloader_random.o
CC src/flash_encrypt.o
CC src/esp_image_format.o
CC src/flash_partitions.o
CC src/secure_boot_signatures.o
CC src/secure_boot.o
CC src/bootloader_flash.o
AR libbootloader_support.a
CC log.o
AR liblog.a
CC spi_flash_rom_patch.o
AR libspi_flash.a
CC esp32/brownout.o
CC esp32/rtc_clk.o
CC esp32/cpu_util.o
AR libsoc.a
CC flash_qio_mode.o
CC bootloader_start.o
AR libmain.a
LD bootloader.elf
esptool.py v2.0
building AT customized partition table at_customize.csv
building AT customized partition table succeed
generating AT customized partition bins to /c/espressif/firmware/esp32-at/build/customized_partitions
generating ble_data.bin: python /c/espressif/firmware/esp32-at/tools/BLEService.py -t /c/espressif/firmware/esp32-at/build/customized_partitions/ble_data.bin /c/espressif/firmware/esp32-at/components/customized_partitions/raw_data/ble_data/example.csv
Traceback (most recent call last):
  File "C:/espressif/firmware/esp32-at/tools/BLEService.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
make: *** [/c/espressif/firmware/esp32-at/components/customized_partitions/Makefile.projbuild:43: /c/espressif/firmware/esp32-at/build/at_customize.bin] Error 1

**Comment by xcguang** [comment]
Hi,
Please install the following python packages with pip: pip install pyyaml xlrd.
This is described in tools/README.md.
