### ISSUE TITLE
small typo mistake in AT docu

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-at#4]
4.2.3
Site 19/53

AT+CIPSTA—Sets the IP Address of the ESP32 Station 

Query Command:  
AT+CIPSTA?
Function: to obtain the IP address of the ESP32 SoftAP.

think must renamed 
ESP32 SoftAP -> ESP32 Station
here too:

Set Command:  
AT+CIPSTA=<ip>,[,<gateway>,<netmask>] 
Function: to set the IP address of the ESP32 SoftAP. 

think must renamed 
ESP32 SoftAP -> ESP32 Station

![small_bug](https://cloud.githubusercontent.com/assets/16070445/22860128/5d3a8538-f0f4-11e6-9a80-5c6c6c9bd376.png)

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
No interest - ok
there a few more mistake things in docu 
but ok - Close it

**Comment by xcguang** [comment]
Sorry for the late reply and thanks for your report.We have fixed the mistake,but have not released it on github.

**Comment by ESP32DE** [comment]
Pity about the wasted time
Will use my time now more meaningfully
