### ISSUE TITLE
Default AT Command GPIO

### ISSUE THREAD

**Issue by klteng** [espressif/esp32-at#40]
The document stated the default AT command is GPIO16 and GPIO17 but these are not the U1RXD and U1TXD in the ESP32 device datasheet.  Am I missing something here?

**Comment by xcguang** [comment]
Hi,
Please refer to http://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf. It is described on page 29.

**Comment by klteng** [comment]
If I read the ESP32 datasheet correctly, the GPIO function is remappable.  Am I riight?

**Comment by xcguang** [comment]
Yes, you can remap it to any pin.
