### ISSUE TITLE
+++ to terminate UART-WiFi passthrough transmission

### ISSUE THREAD

**Issue by Chunghyon** [espressif/esp32-at#47]
Hello,
According th the at-command instruction, +++ will terminate the passthrough transmission.
However it doesn't seem to work neither in TCP nor in UDP mode.
Please let me know how I can exit from the passthrough mode.

Thank you.

**Comment by xcguang** [comment]
Hi, please type `+++` without `\r\n`.

**Comment by Chunghyon** [comment]
Yes, I did but passthrough mode is not terminated.

**Comment by MaJerle** [comment]
Did you wait for 1second after you sent +++? You have to wait before you can start sending commands.

**Comment by Chunghyon** [comment]
hi, MaJerle
Yes... I waited for more than several tens seconds but no change....

**Comment by pawelzwronek** [comment]
Did you send it as fast as possible? In manual you can read typing '+++' from keyboard might not be fast enough. Try paste it from clipboard.

**Comment by xcguang** [comment]
Hi @Chunghyon ,
Does it work well?

**Comment by Chunghyon** [comment]
I made a mistake in my coding. It wroks well.
Sorry for the confusion.
