### ISSUE TITLE
compile failed - Include err

### ISSUE THREAD

**Issue by orshefi** [espressif/esp32-at#49]
Hi All,

I've been trying to compile the esp32_at example with no success.
All the paths have been set properly.
I have all the necessary tools to compile (I think) because I have managed to compile examples from the esp_idf repo before changing the IDF_PATH to the esp_idf that embedded in the esp32_at directory.

The error is as follows:

`                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/ext/atomicity.h:35,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/basic_string.h:39,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/string:52,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/random:40,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_algo.h:66,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/algorithm:62,
                 from /relevant_path/esp/esp32-at/esp-idf/components/cxx/./cxx_guards.cpp:20:
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:47:9: error: 'pthread_t' does not name a type
 typedef pthread_t __gthread_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:48:9: error: 'pthread_key_t' does not name a type
 typedef pthread_key_t __gthread_key_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:49:9: error: 'pthread_once_t' does not name a type
 typedef pthread_once_t __gthread_once_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:50:9: error: 'pthread_mutex_t' does not name a type
 typedef pthread_mutex_t __gthread_mutex_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:51:9: error: 'pthread_mutex_t' does not name a type
 typedef pthread_mutex_t __gthread_recursive_mutex_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:52:9: error: 'pthread_cond_t' does not name a type
 typedef pthread_cond_t __gthread_cond_t;
         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:101:1: error: 'pthread_once' was not declared in this scope
 __gthrw(pthread_once)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:102:1: error: 'pthread_getspecific' was not declared in this scope
 __gthrw(pthread_getspecific)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:103:1: error: 'pthread_setspecific' was not declared in this scope
 __gthrw(pthread_setspecific)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:105:1: error: 'pthread_create' was not declared in this scope
 __gthrw(pthread_create)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:106:1: error: 'pthread_join' was not declared in this scope
 __gthrw(pthread_join)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:107:1: error: 'pthread_equal' was not declared in this scope
 __gthrw(pthread_equal)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:108:1: error: 'pthread_self' was not declared in this scope
 __gthrw(pthread_self)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:109:1: error: 'pthread_detach' was not declared in this scope
 __gthrw(pthread_detach)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:111:1: error: 'pthread_cancel' was not declared in this scope
 __gthrw(pthread_cancel)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:113:1: error: 'sched_yield' was not declared in this scope
 __gthrw(sched_yield)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:115:1: error: 'pthread_mutex_lock' was not declared in this scope
 __gthrw(pthread_mutex_lock)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:116:1: error: 'pthread_mutex_trylock' was not declared in this scope
 __gthrw(pthread_mutex_trylock)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:120:1: error: 'pthread_mutex_unlock' was not declared in this scope
 __gthrw(pthread_mutex_unlock)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:121:1: error: 'pthread_mutex_init' was not declared in this scope
 __gthrw(pthread_mutex_init)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:122:1: error: 'pthread_mutex_destroy' was not declared in this scope
 __gthrw(pthread_mutex_destroy)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:124:1: error: 'pthread_cond_init' was not declared in this scope
 __gthrw(pthread_cond_init)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:125:1: error: 'pthread_cond_broadcast' was not declared in this scope
 __gthrw(pthread_cond_broadcast)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:126:1: error: 'pthread_cond_signal' was not declared in this scope
 __gthrw(pthread_cond_signal)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:127:1: error: 'pthread_cond_wait' was not declared in this scope
 __gthrw(pthread_cond_wait)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:128:1: error: 'pthread_cond_timedwait' was not declared in this scope
 __gthrw(pthread_cond_timedwait)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:129:1: error: 'pthread_cond_destroy' was not declared in this scope
 __gthrw(pthread_cond_destroy)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:131:1: error: 'pthread_key_create' was not declared in this scope
 __gthrw(pthread_key_create)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:132:1: error: 'pthread_key_delete' was not declared in this scope
 __gthrw(pthread_key_delete)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:133:1: error: 'pthread_mutexattr_init' was not declared in this scope
 __gthrw(pthread_mutexattr_init)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:134:1: error: 'pthread_mutexattr_settype' was not declared in this scope
 __gthrw(pthread_mutexattr_settype)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:135:1: error: 'pthread_mutexattr_destroy' was not declared in this scope
 __gthrw(pthread_mutexattr_destroy)
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:659:19: error: '__gthread_create' declared as an 'inline' variable
 __gthread_create (__gthread_t *__threadid, void *(*__func) (void*),
                   ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:659:19: error: '__gthread_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:659:32: error: '__threadid' was not declared in this scope
 __gthread_create (__gthread_t *__threadid, void *(*__func) (void*),
                                ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:659:44: error: expected primary-expression before 'void'
 __gthread_create (__gthread_t *__threadid, void *(*__func) (void*),
                                            ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:660:5: error: expected primary-expression before 'void'
     void *__args)
     ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:660:17: error: expression list treated as compound expression in initializer [-fpermissive]
     void *__args)
                 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:661:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:666:17: error: '__gthread_join' declared as an 'inline' variable
 __gthread_join (__gthread_t __threadid, void **__value_ptr)
                 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:666:17: error: '__gthread_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:666:41: error: expected primary-expression before 'void'
 __gthread_join (__gthread_t __threadid, void **__value_ptr)
                                         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:666:59: error: expression list treated as compound expression in initializer [-fpermissive]
 __gthread_join (__gthread_t __threadid, void **__value_ptr)
                                                           ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:667:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:672:19: error: '__gthread_detach' declared as an 'inline' variable
 __gthread_detach (__gthread_t __threadid)
                   ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:672:19: error: '__gthread_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:673:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:678:18: error: '__gthread_equal' declared as an 'inline' variable
 __gthread_equal (__gthread_t __t1, __gthread_t __t2)
                  ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:678:18: error: '__gthread_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:678:36: error: '__gthread_t' was not declared in this scope
 __gthread_equal (__gthread_t __t1, __gthread_t __t2)
                                    ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:678:52: error: expression list treated as compound expression in initializer [-fpermissive]
 __gthread_equal (__gthread_t __t1, __gthread_t __t2)
                                                    ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:679:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:683:15: error: '__gthread_t' does not name a type
 static inline __gthread_t
               ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h: In function 'int __gthread_yield()':
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:692:33: error: '__gthrw_sched_yield' cannot be used as a function
   return __gthrw_(sched_yield) ();
                                 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h: At global scope:
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:17: error: '__gthread_once' declared as an 'inline' variable
 __gthread_once (__gthread_once_t *__once, void (*__func) (void))
                 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:17: error: '__gthread_once_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:35: error: '__once' was not declared in this scope
 __gthread_once (__gthread_once_t *__once, void (*__func) (void))
                                   ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:50: error: '__func' was not declared in this scope
 __gthread_once (__gthread_once_t *__once, void (*__func) (void))
                                                  ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:59: error: expected primary-expression before 'void'
 __gthread_once (__gthread_once_t *__once, void (*__func) (void))
                                                           ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:696:64: error: expression list treated as compound expression in initializer [-fpermissive]
 __gthread_once (__gthread_once_t *__once, void (*__func) (void))
                                                                ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:697:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:23: error: '__gthread_key_create' declared as an 'inline' variable
 __gthread_key_create (__gthread_key_t *__key, void (*__dtor) (void *))
                       ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:23: error: '__gthread_key_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:40: error: '__key' was not declared in this scope
 __gthread_key_create (__gthread_key_t *__key, void (*__dtor) (void *))
                                        ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:54: error: '__dtor' was not declared in this scope
 __gthread_key_create (__gthread_key_t *__key, void (*__dtor) (void *))
                                                      ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:63: error: expected primary-expression before 'void'
 __gthread_key_create (__gthread_key_t *__key, void (*__dtor) (void *))
                                                               ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:705:70: error: expression list treated as compound expression in initializer [-fpermissive]
 __gthread_key_create (__gthread_key_t *__key, void (*__dtor) (void *))
                                                                      ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:706:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:711:23: error: '__gthread_key_delete' declared as an 'inline' variable
 __gthread_key_delete (__gthread_key_t __key)
                       ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:711:23: error: '__gthread_key_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:712:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:717:24: error: '__gthread_getspecific' declared as an 'inline' variable
 __gthread_getspecific (__gthread_key_t __key)
                        ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:717:24: error: '__gthread_key_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:718:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:723:24: error: '__gthread_setspecific' declared as an 'inline' variable
 __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
                        ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:723:24: error: '__gthread_key_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:723:47: error: expected primary-expression before 'const'
 __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
                                               ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:723:64: error: expression list treated as compound expression in initializer [-fpermissive]
 __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
                                                                ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:724:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:729:32: error: variable or field '__gthread_mutex_init_function' declared void
 __gthread_mutex_init_function (__gthread_mutex_t *__mutex)
                                ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:729:32: error: '__gthread_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:729:51: error: '__mutex' was not declared in this scope
 __gthread_mutex_init_function (__gthread_mutex_t *__mutex)
                                                   ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:736:26: error: '__gthread_mutex_destroy' declared as an 'inline' variable
 __gthread_mutex_destroy (__gthread_mutex_t *__mutex)
                          ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:736:26: error: '__gthread_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:736:45: error: '__mutex' was not declared in this scope
 __gthread_mutex_destroy (__gthread_mutex_t *__mutex)
                                             ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:737:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:745:23: error: '__gthread_mutex_lock' declared as an 'inline' variable
 __gthread_mutex_lock (__gthread_mutex_t *__mutex)
                       ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:745:23: error: '__gthread_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:745:42: error: '__mutex' was not declared in this scope
 __gthread_mutex_lock (__gthread_mutex_t *__mutex)
                                          ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:746:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:754:26: error: '__gthread_mutex_trylock' declared as an 'inline' variable
 __gthread_mutex_trylock (__gthread_mutex_t *__mutex)
                          ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:754:26: error: '__gthread_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:754:45: error: '__mutex' was not declared in this scope
 __gthread_mutex_trylock (__gthread_mutex_t *__mutex)
                                             ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:755:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:775:25: error: '__gthread_mutex_unlock' declared as an 'inline' variable
 __gthread_mutex_unlock (__gthread_mutex_t *__mutex)
                         ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:775:25: error: '__gthread_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:775:44: error: '__mutex' was not declared in this scope
 __gthread_mutex_unlock (__gthread_mutex_t *__mutex)
                                            ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:776:1: error: expected ',' or ';' before '{' token
 {
 ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:786:42: error: '__gthread_recursive_mutex_init_function' declared as an 'inline' variable
 __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t *__mutex)
                                          ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:786:42: error: '__gthread_recursive_mutex_t' was not declared in this scope
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:786:71: error: '__mutex' was not declared in this scope
 __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t *__mutex)
                                                                       ^
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr-default.h:787:1: error: expected ',' or ';' before '{' token
 {
 ^
In file included from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/ext/atomicity.h:35:0,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/basic_string.h:39,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/string:52,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/random:40,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_algo.h:66,
                 from /relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/algorithm:62,
                 from /relevant_path/esp/esp32-at/esp-idf/components/cxx/./cxx_guards.cpp:20:
/relevant_path/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf/bits/gthr.h:151:27: error: expected declaration before end of line
/relevant_path/esp/esp32-at/esp-idf/make/component_wrapper.mk:210: recipe for target 'cxx_guards.o' failed
make[1]: *** [cxx_guards.o] Error 1
/relevant_path/esp/esp32-at/esp-idf/make/project.mk:386: recipe for target 'cxx-build' failed
make: *** [cxx-build] Error 2
`

I'll much appriciate your reply

**Comment by ustccw** [comment]
@orshefi @xamix
the same issue to [issue 48](https://github.com/espressif/esp32-at/issues/48).
Hi, 
this is because the compiler is not compatible. at the beginning of your compile log, it has warning info:
```
WARNING: Toolchain version is not supported: crosstool-NG crosstool-ng-1.22.0-73-ge28a011
Expected to see version: crosstool-NG crosstool-ng-1.22.0-61-gab8375a
```
so you must use the old compiler, called  **crosstool-NG crosstool-ng-1.22.0-61-gab8375a**
you can download the total toolchain  from https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20170330.zip
the old compiler is under the /opt/ directory, you can copy the compiler to your workpath and export it, of course, for convenience, you can work in this workspace.
you will see the following log if you compile the project successfully:
![compileok](https://user-images.githubusercontent.com/24221485/33059549-9d8f173e-cecf-11e7-9862-e815648d4c85.png)

**Comment by orshefi** [comment]
Thank you, the toolchain attached is for windows version, can you attach
the linux toolchain? (sorry for asking I could not find it by myself)

**Comment by ustccw** [comment]
@orshefi 

- for 64-bit Linux:

  https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz

- for 32-bit Linux:

  https://dl.espressif.com/dl/xtensa-esp32-elf-linux32-1.22.0-61-gab8375a-5.2.0.tar.gz

you could see more information in the esp32-at/esp-idf/docs/get-started/linux-setup.rst
