### ISSUE TITLE
AT set up cmds

### ISSUE THREAD

**Issue by santanapablo1975** [espressif/esp32-at#55]
Hi All

In the section
static esp_at_cmd_struct at_custom_cmd[] = {

I am defining some custom setup up commands, now im am using only integers, for example

at.xxx = 1

OK

and it is working, but now I would like if the setup function would receive also strings?

for example at.xxx = "community_name"

Regards

Juan

**Comment by xcguang** [comment]
Hi @santanapablo1975 ,
You can call ```esp_at_get_para_as_str``` to parse string, please refer to the fuchtion 
```at_setupCmdCipupdate``` in main/at_task.c.

**Comment by santanapablo1975** [comment]
Ok thanks, I am going to check it, we can close then the isuue!
