### ISSUE TITLE
esp32-at install for Arduino core?

### ISSUE THREAD

**Issue by mxwang101** [espressif/esp32-at#59]
If we can per-installed  "esp32-at" at some sections of esp32?  
Like installed some fixed hardware modem communicated over the uart port.

When run Arduino app, we can use at command over the uart?

**Comment by mxwang101** [comment]
We do need can run AT commands in Arduino app.

**Comment by xcguang** [comment]
Hi,now we don't support Arduino, and we will evaluate it.

**Comment by mxwang101** [comment]
please，we do need it！

**Comment by FayeY** [comment]
Maybe [arduino-esp32](https://github.com/espressif/arduino-esp32/issues) is a better place to submit this request. So sorry for the inconvenience.
