### ISSUE TITLE
AT+WAKEUPGPIO not available

### ISSUE THREAD

**Issue by Cheong2K** [espressif/esp32-at#68]
ESP8266 has this AT command for host to wake up the Wi-Fi chip, but it seems that ESP32-AT doesn't support this, how to deal with power down for both host and ESP32?

**Comment by xcguang** [comment]
Hi @Cheong2K ,
AT+WAKEUPGPIO is to wakeup from light-sleep, and esp32-at doesn't support light sleep now.

**Comment by Cheong2K** [comment]
Thank you. How do I deal with the power management then? Any document?

**Comment by xcguang** [comment]
Now esp32-at supports modem sleep and deep sleep.  You can choose one mode of them.

**Comment by FayeY** [comment]
Hi, could this [Sleep Modes](https://esp-idf.readthedocs.io/en/latest/api-reference/system/sleep_modes.html#entering-deep-sleep) document help?

**Comment by Cheong2K** [comment]
I am using the AT firmware, I assume that I do not need to recompile the AT firmware, would you consider to add that AT command to the ESP32-AT?

**Comment by xcguang** [comment]
Hi, 
Which sleep mode do you use? Modem sleep needn't wakeup.
Now  esp32-at doesn't support wakeup from deep-sleep, and we will add it as soon as possible.

**Comment by Cheong2K** [comment]
What I want is: in my design, I have a host MCU to control the ESP32 via UART AT commands, the Host MCU sleeps all the time, so if something goes to UART from the ESP32, the Host MCU must be awaken before the ESP32 can send data.

I am not sure I can send data to the ESP32 if it is in modem sleep or deep sleep modes, or I also need to use a GPIO to wake the ESP32 up first?

**Comment by xcguang** [comment]
If in modem sleep mode, you can send data and needn't wake the ESP32, but you must do it if in deep sleep mode.
Now we don't support to wake the host mcu in official bin, and is it possible to wake the host mcu  by UART?

**Comment by xcguang** [comment]
Hi，
How about this issue? I will close it, and you can reopen it if you have any question.Thanks.
