### ISSUE TITLE
small typo in AT docu (AT+CIPSTART)

### ISSUE THREAD

**Issue by pcbreflux** [espressif/esp32-at#7]
In the doku there is a "hidden" feature in the AT+CIPSTART:

in the doku:
[type]: string parameter indicating the connection type: "TCP" or "UDP"

but the Example reveals a next type: 
Example  AT+CIPSTART="SSL","iot.espressif.cn",8443

suggestion for the Doku:
[type]: string parameter indicating the connection type: "TCP", "UDP" and "SSL"

.

**Comment by xcguang** [comment]
Hi,
Thank you very much for your report,we will fix it.

**Comment by FayeY** [comment]
The documentation has been updated [ESP32_AT_Instruction_Set_and_Examples](http://www.espressif.com/sites/default/files/documentation/esp32_at_instruction_set_and_examples_en.pdf).
