### ISSUE TITLE
AT+BLEGATTSSETATTR takes approximately 1 second to process

### ISSUE THREAD

**Issue by kealist** [espressif/esp32-at#74]
I'm not sure if there is a way to optimize processing, but it takes a long time for the AT commands image to process the data from `AT+BLEGATTSSETATTR`.

```
AT+BLEGATTSSETATTR=1,12,,4
>
0xFF FF FF FF (wait one sec)
OK
```

Is there a way to improve this? It seems abnormally long...

**Comment by xiewenxiang** [comment]
@kealist Thanks for your suggestion, We will check it.

**Comment by kealist** [comment]
![timing](https://user-images.githubusercontent.com/5009062/37100300-944ce2fe-21f0-11e8-8a83-b2a67c2f5c44.png)

Here is a diagram from the logic analyzer showing time for reference.   If I need to update 7 characteristics (each 4 bytes), this takes approximately 7 seconds.

**Comment by xiewenxiang** [comment]
We have fixed it, does this problem still exist?
