### ISSUE TITLE
Add a new AT command

### ISSUE THREAD

**Issue by Cheong2K** [espressif/esp32-at#83]
Is it possible to add my own AT commands to the ESP32-AT firmware? How?

**Comment by yake827** [comment]
Yes, it is easy to add your own AT commands,  just refer to https://github.com/espressif/esp32-at/blob/master/main/interface/uart/at_uart_task.c#L474 . This page show how to add uart command， all API can be found in https://github.com/espressif/esp32-at/blob/master/components/at/include/esp_at.h

**Comment by xcguang** [comment]
Hi @Cheong2K ,
Can this issue be closed?
