### ISSUE TITLE
How to use at Bluetooth to connect to the phone？

### ISSUE THREAD

**Issue by FlyingArm** [espressif/esp32-at#88]
I used the AT firmware library and also initialized the Bluetooth related section. However, no Bluetooth device can be found on the phone, resulting in an inability to connect to the esp32 board.
So if you want to connect esp32 Bluetooth to your phone, how do you do it?

**Comment by xiewenxiang** [comment]
Hi,
Maybe you can refer to this document.
[esp32_at_instruction_set_and_examples_en.pdf](https://github.com/espressif/esp32-at/files/1918293/esp32_at_instruction_set_and_examples_en.pdf)

**Comment by FlyingArm** [comment]
I have read the document,and i set the ble to be a client but the phone can't to search it .

**Comment by xiewenxiang** [comment]
You can try the following steps.
```
AT+BLEINIT=2

OK
AT+BLEGATTSSRVCRE

OK
AT+BLEGATTSSRVSTART

OK
AT+BLEADVSTART

OK
```
Now turn on your phone, the app which I was used is `LightBlue`.

**Comment by FlyingArm** [comment]
My phone is Android ,thank you i will test later!

**Comment by FlyingArm** [comment]
But AT+BLEINIT=2 it will set BLE be server ? Why ?

**Comment by xiewenxiang** [comment]
Because most of the phones are BLE client

**Comment by xiewenxiang** [comment]
I your phone is Android , you can use the APP `BLEDeng`

**Comment by xcguang** [comment]
Hi,
I will close this issue, if it still persists, please reopen it, thanks.
