### ISSUE TITLE
The Things here are outdated!

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-at#9]
Hi espressif

we wait now long time for fixes
open the LIBS - ALL!

We are in OpenSource!

The Things here are outdated and hangs extremly!

best wishes
rudi ;-)

**Comment by AMEuser** [comment]
Espressif please fix and update the AT command library.
My company has a milestone for a project that makes use of it on next days!!!
Thank you.

**Comment by ESP32DE** [comment]
Pity about the wasted time
Will use my time now more meaningfully
