### ISSUE TITLE
Reduce TCP Read Delay

### ISSUE THREAD

**Issue by zackgd1024** [espressif/esp32-at#92]
Hi Everyone

I'm using esp32 to access dev-board UART wirelessly in the following way.

![image](https://user-images.githubusercontent.com/9695494/39235364-49dd00b2-48a8-11e8-932a-da50836e5305.png)

In recent test, I found that the delay between esp32 RD request and RD respond is about 250ms in sequential read access.

Is there any way to reduce this delay? Any comment would be very helpful.
Thanks

**Comment by zackgd1024** [comment]
Any comment?

**Comment by xcguang** [comment]
Hi, How do you get 250ms? Sniffer the packet in the air?
