### ISSUE TITLE
Missing CR-LF after descriptor write

### ISSUE THREAD

**Issue by ronangaillard** [espressif/esp32-at#93]
If esp32 is set as BLE server, and that the client connected to it writes to descriptors, serial output of esp 32 will look like : 

```+WRITE:0,1,2,1,2,+WRITE:0,1,3,1,2,+WRITE:0,1,6,1,2,+BLEDISCONN:0,"xx:xx:xx:xx:xx:xx"```

`+WRITE` messages should end with a CR-LF

This bugs does not appear on write to characteristics which effectively end with CR-LF : 
```
+WRITE:0,1,1,,1,
[...]
```

**Comment by xiewenxiang** [comment]
@ronangaillard 
Hi,
Do you use the default ble_data.bin?
Could you provide your operation steps in BLE client?
