### ISSUE TITLE
esp32 Flash using ESP32 DOWNLOAD TOOL Not working ,after fflash

### ISSUE THREAD

**Issue by senthil313** [espressif/esp32-at#95]
hi,
i develop the code using arduino ide...
i generate .bin file for programming...
i used ESP32 DOWNLOAD TOOL ...for flashing our device...
after flash, it reset continuously....
kindly give any other solution for upload code .bin or .hex  format...
![esp32_flash](https://user-images.githubusercontent.com/32504844/40037571-9a54d2f8-582b-11e8-8037-ba411715b721.JPG)
![cmd_esp32](https://user-images.githubusercontent.com/32504844/40037577-a39b0472-582b-11e8-9de3-7b9d817c4b42.JPG)

**Comment by senthil313** [comment]
i change the flash QIO for bootloader_qio.bin and DIO for bootloader.bin...
i change this into reverse also...

![flash_window](https://user-images.githubusercontent.com/32504844/40037619-da67fc44-582b-11e8-82cb-d93f2a58fa94.JPG)

**Comment by xcguang** [comment]
Please change SPI SPEED 40MHz，and try it. Thanks.

**Comment by xcguang** [comment]
Hi,
Is the issue resolved? I will close it because of no update from you for a long time, and you can reopen it if the problem persists. Thanks for your interest in esp32-at.

**Comment by senthil313** [comment]
Hi xcguang,
Yhanks for your reply...
now its working.... follow the Verbose and clear those problems...

**Comment by kapyaar** [comment]
@senthil313 Hi, I am using arduino to generate the bin file and spiffs binary. Do you know the addresses that should be used in this case?
