### ISSUE TITLE
ESP-WROOM-32 AT Bin V1.0

### ISSUE THREAD

**Issue by AlexandreHDK** [espressif/esp32-at#96]
Hello
I'm starting evaluating this board, and I think the binary at https://www.espressif.com/en/support/download/at could be outdated. Where I can download a new version?

**Comment by FayeY** [comment]
Hi,
https://www.espressif.com/en/support/download/at  is our official released AT bins. We are working on the new release now, maybe a new version will be released at the beginning of June.
Thanks.
