### ISSUE TITLE
BLE Class 1, 100M

### ISSUE THREAD

**Issue by mxwang101** [espressif/esp32-at#97]

**Comment by mxwang101** [comment]
Dear All,

ESP32-at works well. But looklike BLE class 2, only coverage small  area. 

Could you tell me how to setup ESP32 BLE Class 1?

**Comment by xiewenxiang** [comment]
Hi @mxwang101 
You can use this command [AT+RFPOWER](https://github.com/espressif/esp32-at/blob/master/docs/ESP32_AT_Commands_Set.md#cmd-RFPOWER).
