### ISSUE TITLE
ESP32 with AT command didn't work

### ISSUE THREAD

**Issue by DIMOOLLA** [espressif/esp32-at#99]

**Comment by DIMOOLLA** [comment]
![cattura](https://user-images.githubusercontent.com/40026125/41095155-dad87e06-6a50-11e8-945b-437f05364434.PNG)

**Comment by DIMOOLLA** [comment]
someone can help me?

**Comment by xcguang** [comment]
Hi,
Please erase entire flash by `make erase_flash` and then `make flash` to download the bin files.

**Comment by xcguang** [comment]
Hi @DIMOOLLA,
Does it work?
